// Todos los textos que se ven, en los dos idiomas. Lo carga todo el mundo antes
// que logica.js: el popup, el service worker y los tests.

const TEXTOS = {
  es: {
    "cantidad": "Cantidad",
    "cantidad.pista": "También vale una cuenta: 20+15, 3*12,50, 100-15% o 2k",
    "cantidad.invalida": "Introduce una cantidad válida",
    "de": "De",
    "a": "A",
    "buscar": "Buscar divisa",
    "buscar.nada": "Ninguna divisa",
    "intercambiar": "Intercambiar divisas",
    "intercambiar.titulo": "Intercambiar divisas ({tecla})",
    "recientes": "Pares recientes",
    "reciente.aria": "Cambiar a {de} → {a}",
    "reciente.fijar": "Fijar {de} → {a}, para que no se vaya",
    "reciente.soltar": "Soltar {de} → {a}",
    "reciente.lleno": "Como mucho {n} pares fijos. Suelta uno antes",
    "resultado": "Resultado",
    "resultado.aria": "Cantidad convertida",
    "resultado.copiar": "Doble clic para copiarlo (con Shift, la frase entera)",
    "copiar": "Copiar",
    "copiar.aria": "Copiar el resultado",
    "copiar.titulo": "Copiar el resultado ({tecla}). Con Shift, la frase entera",
    "copiado.frase": "Frase copiada",
    "copiar.frase": "Copiar frase",
    "copiado": "Copiado",
    "copiar.fallo": "No se pudo",
    "cerrar": "Cerrar",
    "cargando": "Obteniendo tasas…",
    "reintentar": "Reintentar",
    "actualizado": "Act. {fecha}",
    "tasa.alReves": "Pulsa para verla al revés",
    "cambioDia.titulo": "Desde el {fecha}, el último día publicado antes de hoy",
    "pie.tasasDe": "Tasas de",
    "atajos": "Atajos",
    "pct": "{n} %",

    "historial": "Últimas conversiones",
    "historial.cuenta": "Últimas conversiones ({n})",
    "historial.borrar": "Borrar",
    "historial.vacio": "Aún no has convertido nada. Lo que conviertas irá saliendo aquí.",
    "historial.fila": "{cantidad} {from} son {resultado} {to}, {cuando}. Copiar",
    "historial.copiado": "✓ copiado",
    "historial.fallo": "no se pudo",
    "historial.usar": "Volver a ponerla",
    "historial.usarAria": "Volver a poner {cantidad} {from} a {to}",
    "historial.quitar": "Quitar {cantidad} {from} a {to}",

    "comision.titulo": "Comisión de tu banco",
    "comision.rapidas": "Comisiones habituales",
    "comision.otra": "otra",
    "comision.otraAria": "Otra comisión, en tanto por ciento",
    "comision.nota": "Se suma a lo convertido. Las tarjetas suelen cobrar entre un 1 y un 3 %.",
    "comision.anadir": "+ comisión",
    "comision.anadirAria": "Añadir la comisión de tu banco",
    "comision.anadirTitulo": "Añade lo que te cobra el banco por pagar en otra divisa",
    "comision.aria": "Con la comisión del {pct} pagarías {total}. Cambiarla",
    "comision.conTitulo": "Con la comisión de tu banco pagarías {total}",
    "comision.sin": "Sin",
    "comision.sinAria": "Sin comisión",
    "comision.incluida": "con comisión +{pct}",
    "comision.incluidaTitulo": "Las cifras de abajo ya llevan la comisión de tu banco",

    "vistas": "Qué ver debajo del resultado",
    "vista.evolucion": "Evolución de la tasa",
    "vista.extras": "Otras divisas",
    "vista.avisos": "Avisos de tasa",
    "vista.chuleta": "Chuleta de viaje",
    "vista.fecha": "Tasa de un día",
    "vista.timo": "¿Te cambian bien?",

    "rangos": "Periodo del gráfico",
    "rango.7": "7D",
    "rango.7.largo": "7 días",
    "rango.30": "1M",
    "rango.30.largo": "1 mes",
    "rango.90": "3M",
    "rango.90.largo": "3 meses",
    "rango.365": "1A",
    "rango.365.largo": "1 año",
    "grafico": "Gráfico de la tasa. Con las flechas vas día a día y con Enter ves ese día.",
    "grafico.minimo": "Mínimo {valor}",
    "grafico.maximo": "Máximo {valor}",
    "media": "media",

    "momento.bueno": "Buen momento",
    "momento.normal": "Momento normal",
    "momento.malo": "Mal momento",
    "momento.enLaMedia": "en la media",
    "momento.sobre": "{pct} sobre la media",
    "momento.bajo": "{pct} bajo la media",
    "momento.explicacion": "Hoy la tasa es mejor que el {pct} de los días {periodo}. Cuanto más alta, más {to} te dan por cada {from}.",
    "momento.anio": "del último año",
    "momento.dias": "de los últimos {dias}",
    "momento.aria": "{titulo}, {detalle} de {dias} días. {explicacion}",

    "extras.anadir": "Añadir",
    "extras.elegir": "{nombre}. Pulsa para ponerla como destino",
    "extras.aria": "{nombre}: {valor}. Ponerla como destino",
    "extras.semana": "{cambio} en la última semana",
    "extras.quitar": "Quitar {nombre}",
    "bandeja": "Añadir divisa",
    "bandeja.opcion": "Añadir {nombre}",

    "avisos.lista": "Tus avisos",
    "avisos.avisar": "Avisar",
    "avisos.sube": "▲ {from} sube de",
    "avisos.baja": "▼ {from} baja de",
    "avisos.llega": "{from} llega a",
    "avisos.subeDe": "sube de",
    "avisos.bajaDe": "baja de",
    "avisos.pastilla": "Aviso: {from} {sentido} {umbral} {to}. Ir a ese par",
    "avisos.quitar": "Quitar el aviso",
    "avisos.nota": "Te aviso aunque tengas el popup cerrado.",
    "avisos.escribe": "Escribe una tasa, por ejemplo {ejemplo}.",
    "avisos.lleno": "Ya tienes {max} avisos: quita alguno.",
    "avisos.igual": "Pon un valor distinto de la tasa de ahora.",
    "avisos.noSe": "Ese aviso no se puede crear.",
    "avisos.casi": "Está al caer",
    "avisos.falta": "Le falta un {pct} para saltar",
    "avisos.hecho": "Hecho. Te aviso aunque cierres el popup.",
    "avisos.notiTitulo": "1 {from} ya está a {tasa} {to}",
    "avisos.notiSube": "Ha subido de {umbral}, como pediste.",
    "avisos.notiBaja": "Ha bajado de {umbral}, como pediste.",

    "chuleta.aria": "{cantidad} {from} son {valor} {to}. Ponerlo como cantidad",
    "chuleta.titulo": "Chuleta {from} → {to}",
    "chuleta.conComision": "Con la comisión del {pct} de la tarjeta",
    "chuleta.compartir": "Copiar la chuleta, lista para pegar en WhatsApp",
    "chuleta.copiada": "Chuleta copiada. Pégala en el grupo del viaje",

    "fecha.campo": "Día que quieres consultar",
    "fecha.rapidas": "Hace cuánto",
    "fecha.hace": "Hace {texto}",
    "fecha.1": "1 mes",
    "fecha.6": "6 meses",
    "fecha.12": "1 año",
    "fecha.valor": "{cantidad} {from} el {fecha}",
    "fecha.del": "del {fecha}",
    "fecha.hoy": "hoy {valor}",
    "fecha.cambio": "Lo que ha cambiado la tasa desde el {fecha}",
    "fecha.otroDia": "Ese día no hubo tasa; es la del {fecha}",

    "timo.campo": "La tasa que te ofrecen",
    "timo.bien": "Bien",
    "timo.normal": "Normal",
    "timo.caro": "Caro",
    "timo.timo": "Te timan",
    "timo.pierdes": "pierdes {valor}",
    "timo.margen": "Lo que se queda la casa de cambio sobre la tasa real",
    "timo.pista": "Escribe la tasa de la ventanilla y te digo cuánto pierdes.",
    "timo.mismo": "Elige dos divisas distintas.",
    "timo.teDan": "te dan {valor} en vez de {justo}",
    "timo.pagas": "pagas {valor} en vez de {justo}",
    "timo.tarjeta": "Sale mejor con tu tarjeta (+{pct})",
    "timo.aqui": "Sale mejor aquí que con tu tarjeta (+{pct})",
    "timo.alReves": "La has escrito al revés: la leo como 1 {de} = {tasa} {a}",

    "hace.ahora": "ahora",
    "hace.min": "hace {n} min",
    "hace.horas": "hace {n} h",
    "hace.ayer": "ayer",
    "hace.dias": "hace {n} días",
    "dia.hoy": "Hoy",
    "csv.fecha": "Fecha",
    "csv.hora": "Hora",
    "csv.concepto": "Concepto",
    "csv.categoria": "Categoría",
    "cat.comida": "Comida",
    "cat.transporte": "Transporte",
    "cat.alojamiento": "Alojamiento",
    "cat.ocio": "Ocio",
    "cat.compras": "Compras",
    "cat.otros": "Otros",
    "cat.elegir": "Categoría: {nombre}. Cambiarla",
    "cat.lista": "Elige la categoría",
    "cat.filtrar": "{nombre}: {total}, el {pct} del viaje. Ver solo esto",
    "cat.desglose": "En qué se va el dinero",
    "csv.cantidad": "Cantidad",
    "csv.de": "Divisa",
    "csv.resultado": "Resultado",
    "csv.importe": "Importe",
    "csv.a": "En",
    "csv.pago": "Pago",
    "csv.comision": "Comisión",
    "pago.tarjeta": "Tarjeta",
    "pago.efectivo": "Efectivo",
    "pago.elegir": "Pagado con: {nombre}. Pulsa para cambiar",
    "pago.efectivoNota": "En efectivo no se suma la comisión",
    "csv.boton": "CSV",
    "csv.historial": "Descargar las conversiones en CSV, para una hoja de cálculo",
    "csv.gastos": "Descargar los gastos en CSV, para una hoja de cálculo",
    "csv.hecho": "✓ CSV",
    "compartir": "Copiar el resumen del viaje, listo para pegar en WhatsApp",
    "compartir.hecho": "✓ Copiado",
    "compartir.flash": "Resumen copiado. Pégalo en WhatsApp o donde quieras",
    "copia": "Copia de seguridad",
    "copia.abrir": "Copia de seguridad de tus datos",
    "copia.intro": "La extensión está cargada a mano: si borras la carpeta o cambias de ordenador, se pierde lo que has apuntado. Con una copia lo recuperas.",
    "copia.ahora": "Lo que tienes ahora",
    "copia.viaje": "viaje",
    "copia.viajes": "viajes",
    "copia.gasto": "gasto",
    "copia.gastos": "gastos",
    "copia.aviso": "aviso",
    "copia.avisos": "avisos",
    "copia.conversion": "conversión",
    "copia.conversiones": "conversiones",
    "copia.descargar": "Descargar la copia",
    "copia.descargada": "✓ Descargada",
    "copia.archivo": "conversordivisas-copia",
    "copia.restaurar": "Restaurar una copia",
    "copia.soltar": "Arrastra aquí el archivo de la copia",
    "copia.elegir": "o pulsa para elegirlo",
    "copia.deFecha": "Copia del {fecha}",
    "copia.sinFecha": "Copia sin fecha",
    "copia.sustituye": "Sustituye todo lo que tienes ahora por lo de la copia.",
    "copia.si": "Restaurar",
    "copia.no": "Cancelar",
    "copia.hecho": "Restaurada. Abre el popup y lo tendrás todo.",
    "copia.error.json": "Ese archivo no se puede leer: no es una copia.",
    "copia.error.otra": "Ese archivo no es una copia de ConversorDivisas.",
    "copia.error.version": "La copia es de una versión más nueva de la extensión. Actualízala primero.",
    "copia.error.guardar": "No se ha podido guardar. Prueba otra vez.",
    "copia.pie": "Todo se queda en tu navegador: la copia es un archivo tuyo y no se manda a ningún sitio.",
    "compartir.fallo": "No se pudo",
    "compartir.total": "Total: {total} en {n}",
    "compartir.caro": "🏆 Lo más caro: {que}, {valor} ({dia})",
    "compartir.diaMas": "📅 El día que más: {dia}, {valor}",
    "compartir.comisiones": "💳 Comisiones del banco: {valor}",
    "compartir.categorias": "En qué se ha ido",
    "compartir.dias": "Por días",
    "compartir.queda": "💰 Presupuesto: {gastado} de {importe}. Quedan {queda}",
    "compartir.pasado": "💸 Presupuesto: {gastado} de {importe}. Nos hemos pasado {pasado}",
    "csv.archivoHistorial": "conversiones",
    "csv.archivoGastos": "gastos-viaje",
    "csv.archivoViaje": "gastos-{nombre}",
    "dia.ayer": "Ayer",

    "gastos": "Gastos del viaje",
    "gastos.cuenta": "Gastos del viaje ({n})",
    "viajes": "Tus viajes",
    "viajes.cambiar": "Cambiar de viaje",
    "viajes.sinNombre": "Mi viaje",
    "viajes.nuevo": "Nuevo viaje: Japón, Lisboa…",
    "viajes.nuevoAria": "Nombre del viaje nuevo",
    "viajes.crear": "Crear el viaje",
    "viajes.lleno": "Caben {n} viajes. Borra uno para empezar otro",
    "viajes.vacio": "Sin gastos",
    "viajes.renombrar": "Cambiar el nombre de {nombre}",
    "viajes.nombre": "Nombre del viaje",
    "viajes.borrar": "Borrar {nombre}",
    "viajes.seguro": "Borrar",
    "viajes.seguroAria": "Pulsa otra vez para borrar {nombre} con todos sus gastos",
    "gastos.concepto": "Concepto (opcional)",
    "gastos.apuntar": "+ {valor}",
    "gastos.apuntarAria": "Apuntar {cantidad} {from}, que son {valor}",
    "gastos.nada": "Escribe una cantidad arriba para apuntarla",
    "gastos.vacio": "Apunta lo que vas gastando y te sumo el total en tu divisa, con la tasa de cada día.",
    "gastos.vaciar": "Vaciar",
    "gastos.seguro": "¿Seguro?",
    "gastos.n": "{n} gastos",
    "gastos.uno": "1 gasto",
    "gastos.repetir": "Apuntarlo otra vez hoy",
    "gastos.repetirDe": "Apuntar otra vez {concepto} de {cantidad}, hoy",
    "gastos.editar": "Pulsa para cambiar el concepto",
    "gastos.editarDe": "Cambiar el concepto de {concepto}",
    "gastos.media": "Media: {media} al día",
    "gastos.hoyMedia": "Hoy {hoy} · media {media}",
    "gastos.mediaTitulo": "Lo que llevas de media en {dias} días, contando los que no gastaste",
    "gastos.sinConcepto": "Gasto",
    "gastos.quitar": "Quitar {concepto} de {valor}",
    "gastos.quitado": "Quitado: {concepto}, {valor}",
    "gastos.vaciados": "Vaciado: {n}",
    "gastos.deshacer": "Deshacer",
    "gastos.fila": "{concepto}: {cantidad} {from}, {valor}",
    "gastos.comision": "Con la comisión del {pct}",
    "gastos.comisiones": "{importe} en comisiones",
    "gastos.comisionesTitulo": "Lo que se ha quedado el banco con la tarjeta. Los gastos que no guardaron su comisión no cuentan",
    "gastos.efectivo": "{importe} en efectivo",
    "gastos.efectivoTitulo": "Lo que has pagado en efectivo, para saber cuánto sacar",
    "presupuesto.anadir": "+ presupuesto",
    "presupuesto.anadirTitulo": "Ponte un presupuesto y te digo cuánto te queda al día",
    "presupuesto.queda": "Te quedan {queda}",
    "presupuesto.alDia": "{porDia} al día",
    "presupuesto.llega": "llega al {fecha}",
    "presupuesto.quedaCorto": "Quedan {queda}",
    "presupuesto.llegaTitulo": "Al ritmo que llevas te llega hasta el {fecha}. Para llegar al final, {porDia} al día",
    "presupuesto.dia": "Día {dia}/{total}",
    "presupuesto.marca": "La marca es lo que llevarías gastado al acabar hoy, el día {dia} de {total}, yendo parejo",
    "presupuesto.esto": "≈ {dias} días",
    "presupuesto.estoUno": "≈ 1 día",
    "presupuesto.estoPasa": "Te pasas",
    "presupuesto.estoTitulo": "Lo que se lleva este gasto, en días de lo que te queda al día",
    "presupuesto.pasado": "Te has pasado {pasado}",
    "presupuesto.titulo": "{gastado} de {importe}, hasta el {fecha}. Pulsa para cambiarlo",
    "presupuesto.importe": "Cuánto quieres gastar",
    "presupuesto.hasta": "Hasta qué día",
    "presupuesto.desde": "Qué día sales",
    "presupuesto.del": "del",
    "presupuesto.al": "al",
    "presupuesto.guardar": "OK",
    "presupuesto.quitar": "Quitar el presupuesto",
    "presupuesto.notiJusto": "Llevas el {pct} del presupuesto",
    "presupuesto.notiPasado": "Te has pasado del presupuesto",
    "presupuesto.notiQueda": "Te quedan {queda}, {porDia} al día.",
    "presupuesto.notiQuedaSolo": "Te quedan {queda}.",
    "presupuesto.notiPasadoCuerpo": "{gastado} de {importe}: {pasado} de más.",

    "ayuda.titulo": "Atajos de teclado",
    "ayuda.nota": "Si estás escribiendo en un campo, con {alt} delante: {alt}S, {alt}C… (la ayuda, {alt}H).",
    "atajo.intercambiar": "Dar la vuelta al par",
    "atajo.copiar": "Copiar el resultado (con Shift, la frase entera)",
    "atajo.copiarFrase": "Copiar la frase entera",
    "atajo.origen": "Elegir la divisa de origen",
    "atajo.destino": "Elegir la divisa de destino",
    "atajo.vista:evolucion": "Ver el gráfico",
    "atajo.vista:extras": "Ver otras divisas",
    "atajo.vista:avisos": "Ver los avisos",
    "atajo.vista:chuleta": "Ver la chuleta de viaje",
    "atajo.vista:fecha": "Ver la tasa de un día",
    "atajo.vista:timo": "Ver si te cambian bien",
    "atajo.gastos": "Abrir los gastos del viaje",
    "atajo.cuenta": "Dividir la cuenta",
    "atajo.historial": "Ver las últimas conversiones",
    "atajo.deshacer": "Deshacer lo que has quitado",
    "cuenta": "Dividir la cuenta",
    "cuenta.cadaUno": "Cada uno",
    "cuenta.conPropina": "Con propina",
    "cuenta.propina": "Propina",
    "cuenta.propinas": "Propinas habituales",
    "cuenta.sin": "Sin",
    "cuenta.sinAria": "Sin propina",
    "cuenta.otra": "otra",
    "cuenta.otraAria": "Otra propina, en tanto por ciento",
    "cuenta.entre": "Entre",
    "cuenta.menos": "Uno menos",
    "cuenta.mas": "Uno más",
    "cuenta.personas": "{n} personas",
    "cuenta.una": "1 persona",
    "cuenta.pie": "{cuenta} + {propina} de propina = {total}",
    "cuenta.total": "{total} en total",
    "cuenta.nada": "Escribe arriba lo que pone la cuenta",
    "cuenta.redondeo": "Redondeado hacia arriba, para que no falte nada",
    "cuenta.compartir": "Copiar el reparto, listo para pegar en WhatsApp",
    "cuenta.compartir.total": "La cuenta: {total}",
    "cuenta.compartir.propina": "{cuenta} + {propina} de propina ({pct})",
    "cuenta.compartir.cadaUno": "{cada} cada uno, entre {n}",
    "cuenta.copiada": "Reparto copiado. Pégalo en el grupo",
    "atajo.ayuda": "Esta ayuda",

    "idioma.puesta": "puesta por tu idioma",
    "idioma.cambiado": "Ahora en español",
    "ayuda.idioma": "El idioma se cambia con clic derecho en el icono de la barra.",
    "ayuda.flechas": "En la cantidad, ↑ y ↓ suben o bajan 1, y con Shift, 10.",
    "ayuda.seleccion": "En cualquier página, {tecla} convierte lo que tengas seleccionado.",
    "ayuda.sinTecla": "El atajo para convertir lo seleccionado lo tiene otra extensión: cámbialo en chrome://extensions/shortcuts.",
    "menu.idioma": "Idioma",
    "menu.idioma.auto": "Automático (el de Chrome)",

    "insignia.cambio": "{tasa} · {cambio} desde el día anterior",
    "insignia.fecha": "Tasa del BCE del {fecha}",
    "menu.convertir": "Convertir «%s»",
    "menu.insignia": "Mostrar la tasa en el icono",

    "tarjeta": "Conversión de divisa",
    "tarjeta.cita": "«{texto}»",
    "tarjeta.sinDivisa": "Sin divisa en el texto: uso {from}",
    "tarjeta.nada": "No veo ninguna cantidad en lo que has seleccionado.",
    "tarjeta.sinSeleccion": "Selecciona un precio en la página y vuelve a pulsar el atajo.",

    "menu.precios": "Convertir los precios de la página",
    "barra.pista": "Escribe una cantidad: 20 usd, 50 eur a gbp, 100-15% jpy",
    "barra.no": "No lo entiendo. Prueba con 20 usd o 50 eur a gbp",
    "barra.enter": "Enter lo abre en el conversor",
    "precios.uno": "1 precio pasado a {to}",
    "precios.varios": "{n} precios pasados a {to}",
    "precios.nada": "No he encontrado precios en esta página.",
    "precios.quitar": "Quitar",
    "precios.otraVez": "Vuelve a darle al menú para quitarlos",

    "error.tiempo": "La conexión ha tardado demasiado.",
    "error.sinRed": "Sin conexión a internet.",
    "error.servicio": "El servicio de tasas no responde.",
    "error.otro": "No se han podido obtener las tasas.",
  },

  en: {
    "cantidad": "Amount",
    "cantidad.pista": "You can also type a sum: 20+15, 3*12.50, 100-15% or 2k",
    "cantidad.invalida": "Enter a valid amount",
    "de": "From",
    "a": "To",
    "buscar": "Search currency",
    "buscar.nada": "No currency found",
    "intercambiar": "Swap currencies",
    "intercambiar.titulo": "Swap currencies ({tecla})",
    "recientes": "Recent pairs",
    "reciente.aria": "Switch to {de} → {a}",
    "reciente.fijar": "Pin {de} → {a} so it stays",
    "reciente.soltar": "Unpin {de} → {a}",
    "reciente.lleno": "Up to {n} pinned pairs. Unpin one first",
    "resultado": "Result",
    "resultado.aria": "Converted amount",
    "resultado.copiar": "Double-click to copy it (with Shift, the whole sentence)",
    "copiar": "Copy",
    "copiar.aria": "Copy the result",
    "copiar.titulo": "Copy the result ({tecla}). With Shift, the whole line",
    "copiado.frase": "Line copied",
    "copiar.frase": "Copy line",
    "copiado": "Copied",
    "copiar.fallo": "Failed",
    "cerrar": "Close",
    "cargando": "Fetching rates…",
    "reintentar": "Retry",
    "actualizado": "Upd. {fecha}",
    "tasa.alReves": "Click to flip it",
    "cambioDia.titulo": "Since {fecha}, the last published day before today",
    "pie.tasasDe": "Rates from",
    "atajos": "Shortcuts",
    "pct": "{n}%",

    "historial": "Recent conversions",
    "historial.cuenta": "Recent conversions ({n})",
    "historial.borrar": "Clear",
    "historial.vacio": "Nothing converted yet. Your conversions will show up here.",
    "historial.fila": "{cantidad} {from} is {resultado} {to}, {cuando}. Copy",
    "historial.copiado": "✓ copied",
    "historial.fallo": "failed",
    "historial.usar": "Use it again",
    "historial.usarAria": "Use {cantidad} {from} to {to} again",
    "historial.quitar": "Remove {cantidad} {from} to {to}",

    "comision.titulo": "Your bank's fee",
    "comision.rapidas": "Common fees",
    "comision.otra": "other",
    "comision.otraAria": "Another fee, as a percentage",
    "comision.nota": "Added on top of the conversion. Cards usually charge between 1 and 3%.",
    "comision.anadir": "+ fee",
    "comision.anadirAria": "Add your bank's fee",
    "comision.anadirTitulo": "Add what your bank charges for paying in another currency",
    "comision.aria": "With the {pct} fee you'd pay {total}. Change it",
    "comision.conTitulo": "With your bank's fee you'd pay {total}",
    "comision.sin": "None",
    "comision.sinAria": "No fee",
    "comision.incluida": "incl. +{pct} fee",
    "comision.incluidaTitulo": "The figures below already include your bank's fee",

    "vistas": "What to show below the result",
    "vista.evolucion": "Rate history",
    "vista.extras": "Other currencies",
    "vista.avisos": "Rate alerts",
    "vista.chuleta": "Travel cheat sheet",
    "vista.fecha": "Rate on a given day",
    "vista.timo": "Is it a fair rate?",

    "rangos": "Chart period",
    "rango.7": "7D",
    "rango.7.largo": "7 days",
    "rango.30": "1M",
    "rango.30.largo": "1 month",
    "rango.90": "3M",
    "rango.90.largo": "3 months",
    "rango.365": "1Y",
    "rango.365.largo": "1 year",
    "grafico": "Rate chart. Use the arrow keys to move day by day and Enter to open that day.",
    "grafico.minimo": "Low {valor}",
    "grafico.maximo": "High {valor}",
    "media": "avg",

    "momento.bueno": "Good time",
    "momento.normal": "Normal time",
    "momento.malo": "Bad time",
    "momento.enLaMedia": "at the average",
    "momento.sobre": "{pct} above average",
    "momento.bajo": "{pct} below average",
    "momento.explicacion": "Today's rate beats {pct} of the days {periodo}. The higher it is, the more {to} you get for each {from}.",
    "momento.anio": "in the last year",
    "momento.dias": "in the last {dias} days",
    "momento.aria": "{titulo}, {detalle} over {dias} days. {explicacion}",

    "extras.anadir": "Add",
    "extras.elegir": "{nombre}. Click to make it the target",
    "extras.aria": "{nombre}: {valor}. Make it the target",
    "extras.semana": "{cambio} over the last week",
    "extras.quitar": "Remove {nombre}",
    "bandeja": "Add currency",
    "bandeja.opcion": "Add {nombre}",

    "avisos.lista": "Your alerts",
    "avisos.avisar": "Alert me",
    "avisos.sube": "▲ {from} rises above",
    "avisos.baja": "▼ {from} falls below",
    "avisos.llega": "{from} reaches",
    "avisos.subeDe": "rises above",
    "avisos.bajaDe": "falls below",
    "avisos.pastilla": "Alert: {from} {sentido} {umbral} {to}. Go to that pair",
    "avisos.quitar": "Remove the alert",
    "avisos.nota": "You'll be notified even with the popup closed.",
    "avisos.escribe": "Type a rate, for example {ejemplo}.",
    "avisos.lleno": "You already have {max} alerts: remove one first.",
    "avisos.igual": "Pick a value different from the current rate.",
    "avisos.noSe": "That alert can't be created.",
    "avisos.casi": "About to go off",
    "avisos.falta": "{pct} away from going off",
    "avisos.hecho": "Done. You'll be notified even if you close the popup.",
    "avisos.notiTitulo": "1 {from} is now {tasa} {to}",
    "avisos.notiSube": "It has risen above {umbral}, as you asked.",
    "avisos.notiBaja": "It has fallen below {umbral}, as you asked.",

    "chuleta.aria": "{cantidad} {from} is {valor} {to}. Use it as the amount",
    "chuleta.titulo": "Cheat sheet {from} → {to}",
    "chuleta.conComision": "Including the {pct} card fee",
    "chuleta.compartir": "Copy the cheat sheet, ready to paste into WhatsApp",
    "chuleta.copiada": "Cheat sheet copied. Paste it into the trip group",

    "fecha.campo": "Day to look up",
    "fecha.rapidas": "How long ago",
    "fecha.hace": "{texto} ago",
    "fecha.1": "1 mo",
    "fecha.6": "6 mo",
    "fecha.12": "1 yr",
    "fecha.valor": "{cantidad} {from} on {fecha}",
    "fecha.del": "from {fecha}",
    "fecha.hoy": "today {valor}",
    "fecha.cambio": "How much the rate has changed since {fecha}",
    "fecha.otroDia": "No rate that day; this is the one from {fecha}",

    "timo.campo": "The rate you're offered",
    "timo.bien": "Fair",
    "timo.normal": "Normal",
    "timo.caro": "Pricey",
    "timo.timo": "Rip-off",
    "timo.pierdes": "you lose {valor}",
    "timo.margen": "What the exchange office keeps over the real rate",
    "timo.pista": "Type the rate at the counter and I'll tell you what you lose.",
    "timo.mismo": "Pick two different currencies.",
    "timo.teDan": "you get {valor} instead of {justo}",
    "timo.pagas": "you pay {valor} instead of {justo}",
    "timo.tarjeta": "Your card is cheaper (+{pct})",
    "timo.aqui": "Cheaper here than with your card (+{pct})",
    "timo.alReves": "You typed it the other way round: reading it as 1 {de} = {tasa} {a}",

    "hace.ahora": "just now",
    "hace.min": "{n} min ago",
    "hace.horas": "{n} h ago",
    "hace.ayer": "yesterday",
    "hace.dias": "{n} days ago",
    "dia.hoy": "Today",
    "csv.fecha": "Date",
    "csv.hora": "Time",
    "csv.concepto": "What for",
    "csv.categoria": "Category",
    "cat.comida": "Food",
    "cat.transporte": "Transport",
    "cat.alojamiento": "Lodging",
    "cat.ocio": "Fun",
    "cat.compras": "Shopping",
    "cat.otros": "Other",
    "cat.elegir": "Category: {nombre}. Change it",
    "cat.lista": "Pick the category",
    "cat.filtrar": "{nombre}: {total}, {pct} of the trip. Show only this",
    "cat.desglose": "Where the money goes",
    "csv.cantidad": "Amount",
    "csv.de": "Currency",
    "csv.resultado": "Result",
    "csv.importe": "Cost",
    "csv.a": "In",
    "csv.pago": "Paid with",
    "csv.comision": "Fee",
    "pago.tarjeta": "Card",
    "pago.efectivo": "Cash",
    "pago.elegir": "Paid with: {nombre}. Click to change",
    "pago.efectivoNota": "No bank fee on cash",
    "csv.boton": "CSV",
    "csv.historial": "Download the conversions as CSV, for a spreadsheet",
    "csv.gastos": "Download the expenses as CSV, for a spreadsheet",
    "csv.hecho": "✓ CSV",
    "compartir": "Copy the trip summary, ready to paste into WhatsApp",
    "compartir.hecho": "✓ Copied",
    "compartir.flash": "Summary copied. Paste it into WhatsApp or anywhere",
    "copia": "Backup",
    "copia.abrir": "Back up your data",
    "copia.intro": "The extension is loaded by hand: if you delete its folder or switch computers, everything you've saved is gone. A backup brings it back.",
    "copia.ahora": "What you have now",
    "copia.viaje": "trip",
    "copia.viajes": "trips",
    "copia.gasto": "expense",
    "copia.gastos": "expenses",
    "copia.aviso": "alert",
    "copia.avisos": "alerts",
    "copia.conversion": "conversion",
    "copia.conversiones": "conversions",
    "copia.descargar": "Download backup",
    "copia.descargada": "✓ Downloaded",
    "copia.archivo": "conversordivisas-backup",
    "copia.restaurar": "Restore a backup",
    "copia.soltar": "Drop the backup file here",
    "copia.elegir": "or click to choose it",
    "copia.deFecha": "Backup from {fecha}",
    "copia.sinFecha": "Undated backup",
    "copia.sustituye": "This replaces everything you have now with the backup.",
    "copia.si": "Restore",
    "copia.no": "Cancel",
    "copia.hecho": "Restored. Open the popup and it's all there.",
    "copia.error.json": "That file can't be read: it isn't a backup.",
    "copia.error.otra": "That file isn't a ConversorDivisas backup.",
    "copia.error.version": "This backup comes from a newer version of the extension. Update it first.",
    "copia.error.guardar": "Couldn't save it. Try again.",
    "copia.pie": "Everything stays in your browser: the backup is your own file and isn't sent anywhere.",
    "compartir.fallo": "Couldn't copy",
    "compartir.total": "Total: {total} across {n}",
    "compartir.caro": "🏆 Priciest: {que}, {valor} ({dia})",
    "compartir.diaMas": "📅 Biggest day: {dia}, {valor}",
    "compartir.comisiones": "💳 Bank fees: {valor}",
    "compartir.categorias": "Where it went",
    "compartir.dias": "By day",
    "compartir.queda": "💰 Budget: {gastado} of {importe}. {queda} left",
    "compartir.pasado": "💸 Budget: {gastado} of {importe}. {pasado} over",
    "csv.archivoHistorial": "conversions",
    "csv.archivoGastos": "trip-expenses",
    "csv.archivoViaje": "expenses-{nombre}",
    "dia.ayer": "Yesterday",

    "gastos": "Trip expenses",
    "gastos.cuenta": "Trip expenses ({n})",
    "viajes": "Your trips",
    "viajes.cambiar": "Switch trip",
    "viajes.sinNombre": "My trip",
    "viajes.nuevo": "New trip: Japan, Lisbon…",
    "viajes.nuevoAria": "Name of the new trip",
    "viajes.crear": "Create the trip",
    "viajes.lleno": "Up to {n} trips. Delete one to start another",
    "viajes.vacio": "No expenses",
    "viajes.renombrar": "Rename {nombre}",
    "viajes.nombre": "Trip name",
    "viajes.borrar": "Delete {nombre}",
    "viajes.seguro": "Delete",
    "viajes.seguroAria": "Click again to delete {nombre} and all its expenses",
    "gastos.concepto": "What for (optional)",
    "gastos.apuntar": "+ {valor}",
    "gastos.apuntarAria": "Add {cantidad} {from}, which is {valor}",
    "gastos.nada": "Type an amount above to add it",
    "gastos.vacio": "Add what you spend and I'll total it in your currency, at each day's rate.",
    "gastos.vaciar": "Clear",
    "gastos.seguro": "Sure?",
    "gastos.n": "{n} expenses",
    "gastos.uno": "1 expense",
    "gastos.repetir": "Add it again today",
    "gastos.repetirDe": "Add {concepto} of {cantidad} again, today",
    "gastos.editar": "Click to change what it was for",
    "gastos.editarDe": "Change what {concepto} was for",
    "gastos.media": "Avg: {media} a day",
    "gastos.hoyMedia": "Today {hoy} · avg {media}",
    "gastos.mediaTitulo": "Your daily average over {dias} days, counting the ones you spent nothing",
    "gastos.sinConcepto": "Expense",
    "gastos.quitar": "Remove {concepto} of {valor}",
    "gastos.quitado": "Removed: {concepto}, {valor}",
    "gastos.vaciados": "Cleared: {n}",
    "gastos.deshacer": "Undo",
    "gastos.fila": "{concepto}: {cantidad} {from}, {valor}",
    "gastos.comision": "Including the {pct} fee",
    "gastos.comisiones": "{importe} in fees",
    "gastos.comisionesTitulo": "What the bank kept on card payments. Expenses that didn't save their fee aren't counted",
    "gastos.efectivo": "{importe} in cash",
    "gastos.efectivoTitulo": "What you've paid in cash, so you know how much to take out",
    "presupuesto.anadir": "+ budget",
    "presupuesto.anadirTitulo": "Set a budget and I'll tell you how much you have left per day",
    "presupuesto.queda": "{queda} left",
    "presupuesto.alDia": "{porDia} a day",
    "presupuesto.llega": "lasts till {fecha}",
    "presupuesto.quedaCorto": "{queda} left",
    "presupuesto.llegaTitulo": "At your current pace it lasts until {fecha}. To make it to the end, {porDia} a day",
    "presupuesto.dia": "Day {dia}/{total}",
    "presupuesto.marca": "The mark is what you'd have spent by the end of today, day {dia} of {total}, at an even pace",
    "presupuesto.esto": "≈ {dias} days",
    "presupuesto.estoUno": "≈ 1 day",
    "presupuesto.estoPasa": "Over budget",
    "presupuesto.estoTitulo": "What this expense takes, in days of what you have left per day",
    "presupuesto.pasado": "{pasado} over budget",
    "presupuesto.titulo": "{gastado} of {importe}, until {fecha}. Click to change it",
    "presupuesto.importe": "How much you want to spend",
    "presupuesto.hasta": "Until which day",
    "presupuesto.desde": "Which day you leave",
    "presupuesto.del": "from",
    "presupuesto.al": "to",
    "presupuesto.guardar": "OK",
    "presupuesto.quitar": "Remove the budget",
    "presupuesto.notiJusto": "You've used {pct} of your budget",
    "presupuesto.notiPasado": "You're over budget",
    "presupuesto.notiQueda": "{queda} left, {porDia} a day.",
    "presupuesto.notiQuedaSolo": "{queda} left.",
    "presupuesto.notiPasadoCuerpo": "{gastado} of {importe}: {pasado} over.",

    "ayuda.titulo": "Keyboard shortcuts",
    "ayuda.nota": "While typing in a field, add {alt} first: {alt}S, {alt}C… (help is {alt}H).",
    "atajo.intercambiar": "Swap the pair",
    "atajo.copiar": "Copy the result (with Shift, the whole line)",
    "atajo.copiarFrase": "Copy the whole line",
    "atajo.origen": "Choose the source currency",
    "atajo.destino": "Choose the target currency",
    "atajo.vista:evolucion": "Show the chart",
    "atajo.vista:extras": "Show other currencies",
    "atajo.vista:avisos": "Show the alerts",
    "atajo.vista:chuleta": "Show the travel cheat sheet",
    "atajo.vista:fecha": "Show the rate on a given day",
    "atajo.vista:timo": "Check if a rate is fair",
    "atajo.gastos": "Open trip expenses",
    "atajo.cuenta": "Split the bill",
    "atajo.historial": "Show recent conversions",
    "atajo.deshacer": "Undo a removed expense",
    "cuenta": "Split the bill",
    "cuenta.cadaUno": "Each",
    "cuenta.conPropina": "With tip",
    "cuenta.propina": "Tip",
    "cuenta.propinas": "Common tips",
    "cuenta.sin": "None",
    "cuenta.sinAria": "No tip",
    "cuenta.otra": "other",
    "cuenta.otraAria": "Other tip, as a percentage",
    "cuenta.entre": "Split",
    "cuenta.menos": "One fewer",
    "cuenta.mas": "One more",
    "cuenta.personas": "{n} people",
    "cuenta.una": "1 person",
    "cuenta.pie": "{cuenta} + {propina} tip = {total}",
    "cuenta.total": "{total} in total",
    "cuenta.nada": "Type the bill amount above",
    "cuenta.redondeo": "Rounded up, so nobody comes up short",
    "cuenta.compartir": "Copy the split, ready to paste in WhatsApp",
    "cuenta.compartir.total": "The bill: {total}",
    "cuenta.compartir.propina": "{cuenta} + {propina} tip ({pct})",
    "cuenta.compartir.cadaUno": "{cada} each, split {n} ways",
    "cuenta.copiada": "Split copied. Paste it in the group",
    "atajo.ayuda": "This help",

    "idioma.puesta": "set from your language",
    "idioma.cambiado": "Now in English",
    "ayuda.idioma": "Change the language by right-clicking the toolbar icon.",
    "ayuda.flechas": "In the amount, ↑ and ↓ add or take 1, or 10 with Shift.",
    "ayuda.seleccion": "On any page, {tecla} converts whatever you have selected.",
    "ayuda.sinTecla": "Another extension took the shortcut for converting the selection: change it at chrome://extensions/shortcuts.",
    "menu.idioma": "Language",
    "menu.idioma.auto": "Automatic (Chrome's)",

    "insignia.cambio": "{tasa} · {cambio} since the previous day",
    "insignia.fecha": "ECB rate from {fecha}",
    "menu.convertir": "Convert “%s”",
    "menu.insignia": "Show the rate on the icon",

    "tarjeta": "Currency conversion",
    "tarjeta.cita": "“{texto}”",
    "tarjeta.sinDivisa": "No currency in the text: using {from}",
    "tarjeta.nada": "I can't find an amount in what you selected.",
    "tarjeta.sinSeleccion": "Select a price on the page and press the shortcut again.",

    "menu.precios": "Convert prices on this page",
    "barra.pista": "Type an amount: 20 usd, 50 eur to gbp, 100-15% jpy",
    "barra.no": "I don't get it. Try 20 usd or 50 eur to gbp",
    "barra.enter": "Enter opens it in the converter",
    "precios.uno": "1 price converted to {to}",
    "precios.varios": "{n} prices converted to {to}",
    "precios.nada": "I couldn't find any prices on this page.",
    "precios.quitar": "Remove",
    "precios.otraVez": "Use the menu again to remove them",

    "error.tiempo": "The connection took too long.",
    "error.sinRed": "No internet connection.",
    "error.servicio": "The rates service isn't responding.",
    "error.otro": "Couldn't get the rates.",
  },
};

const LOCALES = { es: "es-ES", en: "en-US" };

let idioma = "es";
let formatos = new Map();

// Español para cualquier variante (es-MX, es-419…); para el resto, inglés, que
// es lo que más gente va a entender.
function idiomaPara(etiqueta) {
  return /^es\b/i.test(String(etiqueta ?? "")) ? "es" : "en";
}

// Los nombres de cada idioma van en su propio idioma: si alguien lo ha puesto
// sin querer en uno que no entiende, tiene que poder encontrar el suyo.
const NOMBRES_IDIOMA = { es: "Español", en: "English" };

// Lo que hayas elegido en el menú manda; "auto" o nada, el de Chrome.
function idiomaElegido(guardado, etiquetaChrome) {
  return TEXTOS[guardado] ? guardado : idiomaPara(etiquetaChrome);
}

function ponerIdioma(nuevo) {
  idioma = TEXTOS[nuevo] ? nuevo : "es";
  formatos = new Map();
}

const idiomaActual = () => idioma;
const localeActual = () => LOCALES[idioma];

// Si a una traducción le faltara algo, mejor el español que la clave pelada.
function tr(clave, datos = {}) {
  const texto = TEXTOS[idioma][clave] ?? TEXTOS.es[clave] ?? clave;
  return texto.replace(/\{(\w+)\}/g, (entero, nombre) => (nombre in datos ? String(datos[nombre]) : entero));
}

// Los Intl cuestan de crear y se usan en cada tecla: uno por idioma y opciones.
function formato(Tipo, opciones) {
  const clave = `${Tipo.name}:${JSON.stringify(opciones)}`;
  if (!formatos.has(clave)) formatos.set(clave, new Tipo(localeActual(), opciones));
  return formatos.get(clave);
}

// El español de Intl deja "1650" sin punto y "16.500" con él; en una misma
// pantalla parecía un fallo, así que agrupo siempre.
const numeros = (opciones) => formato(Intl.NumberFormat, { useGrouping: "always", ...opciones });
const fechas = (opciones) => formato(Intl.DateTimeFormat, opciones);
const separadorDecimal = () => (idioma === "en" ? "." : ",");

if (typeof module !== "undefined") {
  module.exports = {
    TEXTOS, LOCALES, NOMBRES_IDIOMA, idiomaPara, idiomaElegido, ponerIdioma, idiomaActual, localeActual, tr, numeros, fechas, separadorDecimal,
  };
}
